fix: specify remote for branch to checkout
I have many different remotes becuase of checking out branches for external contributors. Git is confused because the branch exists on multiple remotes and fails with:

```
error: pathspec 'build/last-successful' did not match any file(s) known to git
hint: 'build/last-successful' matched more than one remote tracking branch.
```

This fixes that error.