fix: add missing @types/mdast dep (#1445)
resolves multiple errors of error TS2307: Cannot find module 'mdast' or its corresponding type declarations.