chore: update lilconfig version in package.json (#967)
For some reason in my dep tree, npm always resolves lilconfig@2.0.4 which has bug with async loading (fixed in 2.0.5: https://github.com/antonk52/lilconfig/commit/0f68c45a9c4c763131117dc86b537349434e2299). 

That bug surfaces in libp2p with the following error:
```
TypeError: `[object Promise]` is not an Option Object
    at module.exports (libp2p/js-libp2p/node_modules/merge-options/index.js:164:10)
    at config (libp2p/js-libp2p/node_modules/aegir/src/config/user.js:168:39)
    at async main (libp2p/js-libp2p/node_modules/aegir/src/index.js:35:22)
```

After I forced 2.0.5 version, npm resolves correct version but this will ensure nobody resolves buggy version